# manyrepo: cucumber/cucumber-expressions-ruby
language: ruby
sudo: false

rvm:
  - 2.3.1
  - 2.2
  - 2.1
  - 2.0
  - 1.9.3
  - jruby-9.1.2.0

before_install:
  - gem update bundler

notifications:
  email:
    - cukes-devs@googlegroups.com
  webhooks:
    urls: # gitter
      - https://webhooks.gitter.im/e/dc010332f9d40fcc21c4
